### PR TITLE
Add some polyfill

### LINKED ISSUE #407: PageContainer component doesn't work on IE10
We need to add `import "babel-polyfill";` to src/PageContainer/components.js because [collection.find](https://github.com/MoOx/phenomic/blob/next/src/PageContainer/component.js#L49) not works in IE10. With polyfill it works :)

### PR DESCRIPTION
**Pull request by thangngoc89**
- Array.prototype.find (IE10)
- String.prototype.endsWith (Safari 8)

Close #407

I disabled eslint in that file. I want a clean copy-paste

### CODE REVIEW

**Comment by MoOx** [comment]
I think I would prefer to include babel-polyfill to avoid having to maintain a list of polyfill. What is the problem with babel-polyfill?

**Comment by thangngoc89** [comment]
Babel-polyfill is big and slow down the initial load. If you go for babel-polyfill,  please include it in boilerplate so that I can remove it. I prefer cdn polyfill,  it smarter and much faster (fastly cdn)

**Comment by MoOx** [comment]
So why not including the cdn polyfill?
Otherwise, we can remove endsWith and find and other problematic code from client code base. Maybe it's even simpler?

**Comment by thangngoc89** [comment]
> So why not including the cdn polyfill?

Well. we can't. #348 must be resolved first.

>  endsWith

No. it's in react-router (or something else I don't remember, but not in phenomic codebase)

> find

Yes. Just use a ponyfill instead of polyfill. 

But by doing so, we are basiclly maintaining a list of polyfill for ES6 features. 

I'll resolve #348 and add cdn polyfill to boilerplate.

**Pull request closed without merging**
