### PR TITLE
Node 6 support

### PR DESCRIPTION
**Pull request by MoOx**

### CODE REVIEW

**Comment by kuzvac** [comment]
Maybe we need notify user on node v6, that phenomic currently not work properly on v6?  Maybe add rule inside package.json?

**Comment by thangngoc89** [comment]
@kuzvac phenomic can work on node 6 properly. I tested it. This PR is about the internal structure to support node 6 on CI build

**Comment by MoOx** [comment]
I tried this morning with fresh node_modules and v6, didn't get any issue so I will try to update this branch and see what happen, maybe now everything has been fixed in deps.

**Comment by kuzvac** [comment]
Hum, yes, its works. I think it's problem on my side. Excuse me :)

**Comment by thangngoc89** [comment]
So it just works without any modification ? Weird

**Comment by MoOx** [comment]
Now, previously it did not. I cleaned cache so we get latest deps patches.

**Comment by thangngoc89** [comment]
Yeah. I think may be there is some patches from upstream

**Pull request merged**
