### PR TITLE
Use a temp folder for node build

### LINKED ISSUE #439: phenomic.node build might create some files in scripts/_
This can happen if you have some files loaded using file-loader.
A cleanup is made for the extracted css (to only keep phenomic.node.bundle.js), so we should add this to the cleanup.

### PR DESCRIPTION
**Pull request by thangngoc89**
Close #439 

There should be an integration test for this. But I don't want to make boilerplate's webpack config more complicated. Do you have any suggestions ?

### CODE REVIEW

**Comment by MoOx** [comment]
What do you think about moving the builded content into node_modules/.cache/phenomic or something like that (AVA does this I think). That would allow us to keep it, and that will be nice with https://github.com/MoOx/phenomic/issues/442#issuecomment-217252645 in mind

**Comment by thangngoc89** [comment]
It's totally fine with be. Need to test to see if it is doable.

**Comment by thangngoc89** [comment]
Do we have any guarantee in codebase that `process.cwd` is the parent folder that contains `node_modules` folder ?

**Comment by MoOx** [comment]
process.cwd should not be used except for test maybe. We have config.cwd in our codebase.

**Comment by MoOx** [comment]
@thangngoc89 do you plan to update this PR according to my first comment?

**Comment by thangngoc89** [comment]
@MoOx could you help me with this? I don't have much time for Phenomic atm :/

**Comment by MoOx** [comment]
Sure. I will handle this.

**Pull request closed without merging**
