### PR TITLE
Add Remark plugin to transform gemoji shortcodes into emoji

### PR DESCRIPTION
**Pull request by azat-io**
I think it would be better if the user be able to use [Gemoji shortcodes](http://www.emoji-cheat-sheet.com/) for converting `:smile:` to :smile:

### CODE REVIEW

**Comment by MoOx** [comment]
Nice idea.
Not sure if this days, it's very useful. I daily use the OS X emoji picker (using cmd+ctrl+space) so I don't really see a direct benefit. Any comments?

**Comment by azat-io** [comment]
I think now many users still use Linux or Windows OS in their laptops (for example like me). And it'll be very helpful for me

**Comment by thangngoc89** [comment]
I'm not sure if this is necessary. If you want this in your website, you can use a custom render. IMHO, the default renderer should be lightweight

**Comment by MoOx** [comment]
@azat-io did you successfully added this via a custom renderer?
Maybe we should expose the default remark plugins list so people can easily inherit it and just add one or 2 plugins?

**Comment by thangngoc89** [comment]
@MoOx that's a good idea since remark's dependencies are defined in phenomic's . If user want to add something, they have to install a bunch of deps (4-5)

**Comment by MoOx** [comment]
Will eventually add that in the docs when #668

**Pull request closed without merging**
