### PR TITLE
Faq: add CSS Modules shared variables example

### PR DESCRIPTION
**Pull request by revolunet**

### CODE REVIEW

**Comment by thangngoc89** [comment]
the code is good but you get the idea wrong. The title should be how to add global variables with cssnext (actually it's postcss-loader). 

CSS Modules is different thing and it's a seperated from cssnext. You can use CSS Modules with any CSS-preprocessor you like,SASS, LESS, Stylus, <insert your css-preprocessor here>. 

You can read more about it here https://github.com/css-modules/css-modules

**Comment by revolunet** [comment]
I fixed the text & hope its better :)

If i have configured LESS support in CSS modules, what should have been the syntax to get the variable from LESS files ? same `var(--name)` ?

**Comment by thangngoc89** [comment]
I dont know LESS. But when using SASS, this is what I would do (straightforward language's syntax) 

```
$some-var = red
```

And in other file, import it with sass syntax.

**Comment by thangngoc89** [comment]
LGTM. cc @MoOx

**Comment by MoOx** [comment]
Going to make some adjustement & move that in the "Getting started" as it's a must have! Thank you! ❤️

**Pull request merged**
