### PR TITLE
Docs: Fix Getting Started link in Setup instruction

### PR DESCRIPTION
**Pull request by thangngoc89**
[skip ci]

### CODE REVIEW

**Comment by MoOx** [comment]
Hum... https://github.com/MoOx/phenomic/commit/79b7508d28aa09846866ae74b86400da00c72cd3

**Comment by MoOx** [comment]
:D

**Comment by thangngoc89** [comment]
Looks like some rebase mess

**Comment by MoOx** [comment]
No there is two link, one at the top, on at the bottom.

**Comment by thangngoc89** [comment]
Haha

**Pull request merged**
