### PR TITLE
Update eslint-config-recommended

### LINKED ISSUE #838: Linter errors in quickstart example
I'm using v0.17.11 on Sierra and I'm running this example:

https://phenomic.io/docs/setup/

When I run `npm start` the site compiles fine and the browser opens as expected. But when I check my terminal I see tons of linter errors like these:

```
> phenomic start

ℹ Phenomic is starting +0.18s
✔ Development server listening on http://0.0.0.0:3333/ +0.72s
✖ Updated with warnings

⚠ Warning in ./scripts/phenomic.browser.js

./scripts/phenomic.browser.js
  2:1  error  Definition for rule 'react/no-find-dom-node' was not found          react/no-find-dom-node
  2:1  error  Definition for rule 'react/display-name' was not found              react/display-name
  2:1  error  Definition for rule 'react/jsx-no-undef' was not found              react/jsx-no-undef
  2:1  error  Definition for rule 'react/jsx-uses-react' was not found            react/jsx-uses-react

```

### PR DESCRIPTION
**Pull request by montogeek**
This update fixes building errors with the latest Phenomic installation.

Fixes #838

### CODE REVIEW

**Comment by MoOx** [comment]
I would like to get a failure on CI before "fixing" this. Thanks for this anyway as I was missing it.

**Comment by montogeek** [comment]
Cool!

**Comment by MoOx** [comment]
First things first https://github.com/yannickcr/eslint-plugin-react/pull/925 :)

**Comment by MoOx** [comment]
Closed by #841

**Pull request closed without merging**
