### PR TITLE
Add MoonMail to showcase

### PR DESCRIPTION
**Pull request by alexandresaiz**
Thanks!

### CODE REVIEW

**Comment by MoOx** [comment]
@alexandresaiz Thanks! Looks really good! Nice work :)

Note: I remove some tags as they are reserved to all websites (the idea is too only keep commons tags).

**Comment by alexandresaiz** [comment]
@MoOx thanks!

**Comment by MoOx** [comment]
Will be online on next release (website is updated on each release). Hopefully tonight :)

**Comment by alexandresaiz** [comment]
@MoOx did you have a chance to move this live?

**Comment by MoOx** [comment]
Will cut a release in a moment ;)

**Pull request merged**
