### PR TITLE
Optimistic loading (new way to display loading state)

### LINKED ISSUE #824: UX improvement: Even FASTER Page Loading
Right now we have the [generic loading component](https://github.com/MoOx/phenomic/blob/36b03832dde5cf3a11d1b3480f15935172697060/src/components/PageContainer/component.js#L228) which is good but I was thinking about ways to make loading appear even faster for visitors.

Facebook loads the layout with phony loading state text. Example:

image

The effect makes the pages feel like they are loading faster to the user

**So the idea here is:**

If you build your layout components with default loading states, we could basically show the layout instantly when a link is clicked.
1. Visitor clicks link
2. Layout XYZ with prop `phenomicLoading={true}` (or something) renders instead of default generic `<PageLoading>` component
3. After `xyz.json` data is finished fetching & loads, the real layout component just refreshes with the content
4. Visitor is flipping amazed at how fast this site is

While this doesn't technically speed up anything, the perceived site performance would be much faster.

**What do you think?**

Possible implementation: 

We could check [here](https://github.com/MoOx/phenomic/blob/36b03832dde5cf3a11d1b3480f15935172697060/src/components/PageContainer/component.js#L228) is the requested Layout has the reserved `phenomicLoading` propType defined and if so, use it as loading component. If `phenomicLoading` propType is not defined use the default generic `<PageLoading>` component

B/c this would require some work/logic in layouts, this would of course be optional and not required if people just want a generic loading state component as it works now.

Related: https://github.com/MoOx/phenomic/issues/587

### PR DESCRIPTION
**Pull request by MoOx**
Now, if you remove your ``PageLoading`` layouts, you will automatically receive partial data in the correct (future) layout (only head, body won't be defined until ``isLoading`` is != true).

phenomic-optimistic-loading

Should not be a breaking change if you do still use ``PageLoading``.

If you still use ``PageLoading``, you can define a static property in some layouts to tell Phenomic to send an ``isLoading`` props to your specific layout instead of using ``PageLoading`` for this specific transition.

You can refer to [the minimal change you can do in the docs code](https://github.com/MoOx/phenomic/commit/66884e13a69ce6d30505454b763faca543c62b2c) if you want to replace ``PageLoading`` usage by optimistic loading via ``isLoading`` props.

This probably allows you to handle page transition (ref #587) since current layout won't be unmounted.

Closes #836
Closes #824

### CODE REVIEW

**Comment by MoOx** [comment]
@DavidWells does this looks good to you?

**Comment by DavidWells** [comment]
Looks great!

**Comment by MoOx** [comment]
Next time feel free to approve the PR via the dedicated github feature :)

**Comment by montogeek** [comment]
Oh la la!

**Comment by DavidWells** [comment]
@moox Where is that button? =P I've haven't ever had to use that.

**Pull request merged**
