### PR TITLE
Update offline-plugin to the latest

### LINKED ISSUE #905: offline-plugin v4 release
@MoOx hey! I recently released `v4` of `offline-plugin`. Would you like to update to it or you are comfortable with you custom branch?

### PR DESCRIPTION
**Pull request by NekR**
Closes #905

### CODE REVIEW

**Comment by MoOx** [comment]
Thank you!

**Comment by MoOx** [comment]
Actually it seems with latest version of something, it's not working on node 4. Any idea @NekR ? https://travis-ci.org/MoOx/phenomic/jobs/195448787#L1010

**Comment by NekR** [comment]
Hmm.. Not sure, I have all tests passed on Node 4 both on Windows and Linux. Might it be something else, not offline-plugin?

**Comment by MoOx** [comment]
We are using yarn so the only diff for the passing and not passing build should be the version of node.
https://travis-ci.org/MoOx/phenomic/builds/195448785
Here passing for node 6 and not for node 4.

**Comment by NekR** [comment]
Yeah, I see it throws `Error: OfflinePlugin: Plugin's runtime wasn't added to one of your bundle entries. See this https://goo.gl/YwewYp for details.`, that's weird especially that it happens on Node 4 only. I'll debug it.

**Comment by MoOx** [comment]
Thanks for your help.

**Comment by NekR** [comment]
@MoOx btw, can you try re-build on that test? Because I don't see it failing on my commit but failing on `Base theme: Add fb/twitter card image support` commit so that's totally weird.

**Comment by NekR** [comment]
Okay, just tried it, but I'm not able to repro this locally on macOS with Node 4. Are you able to do so?

**Comment by MoOx** [comment]
I am currently able to reproduce this.

**Comment by MoOx** [comment]
I found the issue. In short it's because of the way phenomic is using itself (there is 2 offline-plugin in 2 different node_modules and that's causing an issue). Weird it's "random". Thanks for your time and sorry for the false alarm!

**Pull request merged**
