### PR TITLE
shorten shell commands in doc

### PR DESCRIPTION
**Pull request by doodzik**
shorten shell commands in the docu by using the $_ variable.

http://unix.derkeiler.com/Newsgroups/comp.unix.shell/2008-10/msg00283.html

### CODE REVIEW

**Comment by MoOx** [comment]
Does this work with zsh?

**Comment by doodzik** [comment]
@MoOx yes

**Comment by MoOx** [comment]
Thanks (I learned a thing) but I will pass. I am afraid it add more confusion. Anyway, 1.0 will have a tool to avoid this long command ;)

**Comment by doodzik** [comment]
What is your estimate on the release date of 1.0?

What do you think of stripping the docu from fill words (just, simple, easy, ect.) to make it sound more technical?

**Comment by MoOx** [comment]
@doodzik no ETA for 1.0 yet.

I don't want a 100% technical doc, but I guess we can do the following:

Getting Started: noob friendly not 100% technical + Technical docs ?

**Comment by doodzik** [comment]
Ok. We can evaluate it for a page in the docs and evaluate it then.
But I would do it after the released, because the docs are going to be change.

**Pull request closed without merging**
