### PR TITLE
`join-uri` now `path-to-uri`.

### PR DESCRIPTION
**Pull request by ezralalonde**
+ Renamed `join-uri` to `path-to-uri`
+ Made `path-to-uri` internal-only
+ Exported `url-join` publicly in place of `join-uri`
+ Updated docs and boilerplate

Discussion at 
+ https://github.com/MoOx/phenomic/issues/489

### CODE REVIEW

**Comment by thangngoc89** [comment]
Sorry for late comment. But naming the internal utility path-to-uri doesn't make sense to me. As I can see from the original issue, join-uri joins urls start with protocol incorrectly. Why don't we join treat it as a special case for join-uri ?

**Comment by ezralalonde** [comment]
All `join-uri` does is join arguments with a '/' and strip out extra slashes and transform '\' to '/' in windows paths, not true URI joining. The name `path-to-uri` is meant to show that, rather than applying to all URIs, it really only works for filepaths that need to be represented as URIs. In paths a `//` is never valid, so the resulting URI should never have a `//` in it. Similarly, real URIs should encode '\' as '%5C' (or whatever), which won't work for our case of getting windows paths to URIs, obviously.

I agree that the name is maybe a little weird, but names are hard. I don't think it's captured any better by `join-uri`, as this makes people thinking that you're *actually joining URIs*. Maybe `join-path-as-uri` or some-such is a better alternative, I don't really care that much, personally.

There's some additional discussion at https://github.com/MoOx/phenomic/pull/492 that touches on this a little bit.

The internals, as far as I know, deal in relative "URIs" only, and have no need to deal with the mess of real URIs. This makes perfect sense. There's also a function that works perfectly for this need: `join-uri`/`path-to-uri`/whatever-the-best-name-is.

If you "fix" the implementation of the current `join-uri`/`path-to-uri` function to support the protocol, then you end up breaking as much as you fix, as there are a number of places where stripping two leading slashes is the expected/required behaviour, since they are coming from windows/posix paths, and not "real" URIs.

It is currently, I believe, easiest/cleanest to have two functions:

1. One does what phenomic wants internally (basically fixing paths into usable URI chunks) for paths
2. One that does full-blown URI joining in all its glory, for when you actually need URIs.

Mixing these functions not only hard to get right but, one could argue, *wrong*, since they are different things. For example, an actual URI joiner would escape the backslashes, not replace them with a forward-slash, as `path-to-uri` *must* do to work as advertised on Windows. At best, I think, we could just make the URI joining wrong in increasingly subtle ways, but it's going to be a lot of effort for (in my opinion) very little gain.

The only case for 2 so far is "og:url" and whatever else is in "user space". You could argue that phenomic should not export joinUri at all, and that users could simply use `join-url` where they please, but it may have some effects on backward-compatibility and upgrading.

Note that you could definitely isolate the use of `path-to-uri` better than I have, and replace several calls with a real URI joiner if you wished. As it stands, I've done so in the most brute way possible, but it at least promises that nothing breaks from the change.

If there's something I'm not aware of, or my reasoning or implementation (or anything else) is off, please let me know. I could be way off base.

**Comment by ezralalonde** [comment]
PS. The test at https://ci.appveyor.com/project/MoOx/phenomic/build/1825 is, weirdly, failing. It passes locally (on my linux box) and basically asserts that the current observed behaviour (stripping the leading `//`) isn't happening. I blame windows?

**Comment by thangngoc89** [comment]
Yeah. Thanks for the long and great explanation. This is PR is the best way for doing this. Also, when test fails on appveyor. You blame windows. It sucks.

**Comment by thangngoc89** [comment]
I took a look at the failing test. I think maybe this is a bug of nodejs path.join ? Since we do nothing rather than wrapping that library. I'll find a windows box and test it.

**Comment by MoOx** [comment]
The failure looks like it's a node inconsistency.

**Comment by MoOx** [comment]
So we should probably replace // by / ourselves.

**Comment by ezralalonde** [comment]
I believe that I've addressed the offending test/platform difference by forcing the platforms to act the same. Node's "path" is different for the platforms, and likely the cause of error.

This attempt:

1) Manually replaces \\ with /, as we'd been doing, but in all cases instead of just win32
2) Calls `path.join`, as we'd been doing, but forces it to always use the POSIX join (`path.posix.join`), so it's no longer platform-dependent
3) calls `normalize` (`path.posix.normalize`) on the resulting path, thereby de-duping our slashes.

I don't have a Windows box to test on; I apologize if it's still not passing.

**Comment by MoOx** [comment]
Thanks @ezralalonde 
This lgtm this way.
@thangngoc89 thoughts?
If you are ok, I can merge and cut a patch release.

**Comment by thangngoc89** [comment]
LGTM. thanks a lot @ezralalonde

**Comment by MoOx** [comment]
Released as 0.12.3

**Pull request merged**
