### PR TITLE
Internal: Replace Node 5 by Node 6 on CI

### PR DESCRIPTION
**Pull request by MoOx**
Blocked by : 

- [x] https://github.com/appveyor/ci/issues/770
- [x] https://github.com/tschaub/mock-fs/issues/106

### CODE REVIEW

**Comment by thangngoc89** [comment]
Another blocker
https://github.com/tschaub/mock-fs/issues/106

**Comment by tschaub** [comment]
If you upgrade to mock-fs@3.9.0, you should be able to polish this off.

**Comment by MoOx** [comment]
Now it's seems that linked webpack is causing the issue (the error comes from the fact that 2 webpacks deps are used, if my memory is correct, that why we use symlink, due to the fact that our test are run in a subfolder, and not a parent folder, like in real life).

**Comment by thangngoc89** [comment]
Yeah. I know. I suppose because of the way node 6 resolve dependencies.

**Pull request closed without merging**
