### PR TITLE
Internal: improve release process by pushing a master up to date

### PR DESCRIPTION
**Pull request by MoOx**
Currently, I always forget to update master branch, and master generate
the docs via travis. So this “trick” should help to avoid this
oversight.

### CODE REVIEW

**Comment by thangngoc89** [comment]
Are you sure about `git rebase next` ?

I think it must be `git merge next`

**Comment by MoOx** [comment]
I am using rebase for a few versions.
Since nothing has changed on master, it just add commits. Merge will create a merge commit, and merge commit sucks. No? (I am not a git pro)

**Comment by thangngoc89** [comment]
> Merge will create a merge commit, and merge commit sucks

No. The merge commit thing is the Github shit. (I do this all the time, but you should double check this)

Using rebase can change the commit hash if we aren't careful

**Comment by MoOx** [comment]
Ok, will try by hand for the next release and will see.

**Comment by MoOx** [comment]
I used merge and it is good.

**Pull request merged**
