### PR TITLE
[WIP] Remove restriction on babel-register hook

### LINKED ISSUE #450: Consider using babel-node instead of babel to avoid the *.babel.js need in node context
File consumed via webpack build don't need this, but since we removed babel-plugin-webpack-loaders, I also removed babel-node.
We should try using it back and check perfs. If same result (or almost, since require hook is already on, to handle those *.babel.js via https://github.com/tkellen/node-interpret) we can add it back.

### PR DESCRIPTION
**Pull request by thangngoc89**
Closes #450

### CODE REVIEW

**Comment by MoOx** [comment]
By doing that we could remove babel.js extension from docs & boilerplate & tell people to do it right?

**Comment by thangngoc89** [comment]
Yep

**Comment by montogeek** [comment]
Can we merge this?

**Comment by MoOx** [comment]
Tests are red. We should rebase on master, then fix the build :)
I guess you can continue iterating on this branch since you have the right to!

**Pull request closed without merging**
