### PR TITLE
Removed: webpack build notifications

### LINKED ISSUE #859: Allows possibility of disabling desktop notification
As I asked on gitter, can we expect a configuration option or something like that, that disable desktop notification ?

Thanks

### PR DESCRIPTION
**Pull request by MoOx**
If you want to add notifications back, please directly use
[webpack-notifier](https://www.npmjs.com/package/webpack-notifier)

Closes #859

### CODE REVIEW

**Comment by montogeek** [comment]
I wanted it behind a flag in config, it is really useful, if for some reason it becomes annoying you could just disable it

**Comment by MoOx** [comment]
I might add better notifications more accurate, with Phenomic icon.

**Comment by MoOx** [comment]
(like Jest does)

**Comment by montogeek** [comment]
Thats better!

**Comment by MoOx** [comment]
Failure on appveyor is realted to jest-snapshot update, no big deal (fixed in master)

**Pull request merged**
