### PR TITLE
Add netlify-pages and netlify-cms in docs

### PR DESCRIPTION
**Pull request by xuopled**

### CODE REVIEW

**Comment by MoOx** [comment]
Thanks! (I will make minor changes before putting this online).

**Comment by xuopled** [comment]
Your are welcome. Of course, maybe I did not respect your docs guideline very well

**Comment by MoOx** [comment]
No everything is fine, I will just change url I think (and replace # (h1), by ## (h2) as the h1 is the 'title') ;)

**Comment by xuopled** [comment]
Great, thank you

**Pull request merged**
