### PR TITLE
(content-loader) plugins !

### LINKED ISSUE #260: Plugins for collection-loader
# How will it work ?

Mutate `textData` (need a better name) directly to add/ remove fields of json files programtically . If return null, don't emit this file or add it to collection.

# Default public plugins

Put them in  ( `statinamic/lib/content-loader/plugins/*`) 

- Markdown renderer
- Description renderer #251 
- Don't build draft post on production #111 

Some ideas for plugin:

- Others renderer with description renderer as well (ASCIIDoc, ...)

# Backlog 

Adding new files to collection should be easy (for tagging,...)

### PR DESCRIPTION
**Pull request by MoOx**
- content-loader -> phenomic-loader (+ simplify the place to read config in webpack config)
- phenomic-loader-plugin-* + phenomic-loader-preset-* (in order to prepare #598 ;) )
- default to phenomic-loader-preset-markdown 

- changes: https://github.com/MoOx/phenomic/blob/9b4f677/CHANGELOG.md
- docs: https://github.com/MoOx/phenomic/blob/9b4f677/docs/content/docs/usage/plugins.md

Closes #260 #547

### CODE REVIEW

**Comment by MoOx** [comment]
I still need to add some docs on how to write plugins ;)

**Comment by thangngoc89** [comment]
This is a long waited PR. Thank you

**Comment by MoOx** [comment]
Huge update:
- content-loader -> phenomic-loader (+ simplify the place to read config in webpack config)
- phenomic-loader-plugin-* + phenomic-loader-preset-*  (in order to prepare #598 ;) )
- default to phenomic-loader-preset-markdown 
- docs!

If nobody have time for a full review, at least take a look to docs/changelog update and tell me if something is not clear/wrong.

Would love to merge & release in the beginning of the week.

**Comment by thangngoc89** [comment]
I had a brief look at the changes. It's quite impressive about what you've done here. Great job. So now phenomic can marketing itself as asciidocs or whatever static site generator out of the box. With this PR I think monorepo is a must. I don't want to install a bunch of plugins and its deps that I don't need.

I'll take a closer look this weekend at the code

**Comment by MoOx** [comment]
Yeah I definitely plan to split phenomic and provides more presets like phenomic-loader-preset-asciidocs or whatever people use :D
I don't want to have unused deps neither ;)

**Comment by MoOx** [comment]
@thangngoc89 (or any other watchers) do you have time to review this? I would like to merge and release this if the api looks good to any of you :)

**Comment by thangngoc89** [comment]
:+1:  LGTM

**Pull request merged**
