### PR TITLE
Wrong 'sw-register.js' path when website is not at domain's root

### PR DESCRIPTION
**Pull request by thangngoc89**

### CODE REVIEW

**Comment by MoOx** [comment]
We need a test to avoid a regression in the future.

**Comment by thangngoc89** [comment]
I don't know how to test that file. Do you ?

**Comment by MoOx** [comment]
Add a new use case here with SW on and a base url https://github.com/MoOx/phenomic/blob/next/src/static/to-html/__tests__/url-as-html.js

**Comment by thangngoc89** [comment]
You're right. :+1: I added a test case in #348 . So I'll close this continue overthere.

**Comment by MoOx** [comment]
Maybe we should fix this issue independently? To avoid the pain of relying on a major breaking change?

**Comment by thangngoc89** [comment]
Actually, this PR is unneeded. The baseUrl was added later in the same file. And I didn't notice about that.

**Comment by MoOx** [comment]
So false alarm :)

**Pull request closed without merging**
