### PR TITLE
Internal: Fix regression with path-to-uri introduced in #500

### LINKED ISSUE #502: Regression with 0.12.3: path.posix does not exist in the browser
This breaks everything on the client side.

@ezralalonde any idea how to handle this without path.posix? (I don't have much time atm).

Meanwhile, I tagged 0.12.2 as the latest version.

### PR DESCRIPTION
**Pull request by thangngoc89**
Close #502

### CODE REVIEW

**Comment by MoOx** [comment]
So here you are just providing the posix behavior by hand? @ezralalonde thoughts?

**Comment by thangngoc89** [comment]
@MoOx Yes. I'm providing posix behavior by hand

**Comment by ezralalonde** [comment]
Sorry for the oversight. *C'est la vie*.

This seems fine to me; I like this version the most so far.

Looking at the difference between `posix.join` and `win32.join`, `win32` has a special case for network/UNC paths, which is what was causing platform-dependent problems.

Having "/" and "\" in the regex, and de-duping before `join` makes both `win32.join` and `posix.join` act the same, as far as I can tell, since the network/UNC case is avoided.

**Comment by MoOx** [comment]
Thanks you guys!

**Pull request merged**
